=== jludvice/FaFram8/deployer/src/test/resources/config.scheme.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="org.jboss.fuse.qa"
		   xmlns="org.jboss.fuse.qa"
		   elementFormDefault="qualified">


	<xs:element name="fafram">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="framework" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="patchVersion" type="xs:string" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="container" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="parent" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<xs:element name="username" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<xs:element name="password" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<xs:element name="node" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="host" type="xs:string" use="required"/>
									<xs:attribute name="username" type="xs:string" use="required"/>
									<xs:attribute name="password" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:all>
						<xs:attribute name="instances" type="xs:int"/>
						<xs:attribute name="type" type="containerType"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:simpleType name="containerType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="root"/>
			<xs:enumeration value="child"/>
			<xs:enumeration value="ssh"/>
		</xs:restriction>
	</xs:simpleType>


</xs:schema>

=== jludvice/FaFram8/deployer/src/test/resources/ParserTestConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<fafram xmlns="org.jboss.fuse.qa"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="org.jboss.fuse.qa  config.scheme.xsd">

	<framework></framework>

	<container type="root" instances="1">
		<username>admin</username>
		<password>admin</password>
		<name>root1</name>
		<node host="openstack" username="fuse" password="fuse"/>
	</container>

	<container instances="1" type="ssh">
		<name>fafram8-ssh-container-a</name>
		<parent>root1</parent>
		<node host="openstack" username="fuse" password="fuse"/>
	</container>

	<container instances="1" type="ssh">
		<parent>root1</parent>
		<name>fafram8-ssh-container-b</name>
		<node host="openstack" username="fuse" password="fuse"/>
	</container>

</fafram>

=== jludvice/FaFram8/deployer/src/test/resources/OpenStackProvisionTestConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<fafram xmlns="org.jboss.fuse.qa"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="org.jboss.fuse.qa  config.scheme.xsd">

	<framework></framework>

	<container type="root" instances="1">
		<!-- Note the root container name is always "root" -->
		<name>ecervena-root123</name>
		<username>fafram</username>
		<password>fafram</password>
		<node host="openstack" username="fuse" password="fuse"/>
	</container>

	<container instances="1" type="ssh">
		<name>ecervena-node1123</name>
		<username>fafram</username>
		<password>fafram</password>
		<parent>ecervena-root123</parent>
		<node host="openstack" username="fuse" password="fuse"/>
	</container>

</fafram>
