=== jludvice/FaFram8/deployer/src/test/resources/configuration.scheme.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   elementFormDefault="qualified">

	<!-- -->
	<!--<xs:attribute name="profile" type="xs:string" default="default" />-->
	<!--<xs:attribute name="version" type="xs:string" />-->

	<xs:complexType name="ssh">
		<xs:attribute name="username" type="xs:string"/>
		<xs:attribute name="password" type="xs:string"/>
		<xs:attribute name="host" type="xs:string"/>
		<xs:attribute name="port" type="xs:integer"/>
	</xs:complexType>

	<xs:complexType name="brokerNetworksType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="network">
				<xs:complexType>
					<xs:attribute name="group" type="xs:string"/>
					<xs:attribute name="username" type="xs:string"/>
					<xs:attribute name="password" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="brokerType">
		<xs:all>
			<xs:element name="networks" type="brokerNetworksType" minOccurs="0"></xs:element>
		</xs:all>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="group" type="xs:string"/>
		<xs:attribute name="kind" type="xs:string"/>
		<xs:attribute name="data" type="xs:string"/>
		<xs:attribute name="autoName" type="xs:boolean"/>
	</xs:complexType>

	<!-- definition of container type -->
	<xs:complexType name="containerType">
		<xs:all>
			<xs:element name="parent" type="xs:string" minOccurs="0"/>
			<xs:element name="ssh" type="ssh" minOccurs="0"/>
			<xs:element name="broker" type="brokerType" minOccurs="0"/>
			<xs:element name="path" type="xs:string" minOccurs="0"/>
			<xs:element name="env" type="xs:string" minOccurs="0"/>
			<xs:element name="resolver" type="xs:element" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name='type' type="xs:string">
			<xs:simpleType>
				<xs:restriction>
					<xs:enumeration value="ROOT"/>
					<xs:enumeration value="CHILD"/>
					<xs:enumeration value="SSH"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="autoName" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="containersType">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element name="container" type="containerType"/>
		</xs:sequence>
		<xs:attribute name="containerCount" type="xs:integer"/>
	</xs:complexType>

	<!-- Definitions of global fafram configuration-->

	<xs:complexType name="frameworkType">
		<xs:all>
			<xs:element name="host" type="ssh" minOccurs="0"/>
			<xs:element name="fuse" type="ssh" minOccurs="0"/>
			<xs:element name="fuse.group" type="xs:string" minOccurs="0"/>
			<xs:element name="fuse.id" type="xs:string" minOccurs="0"/>
			<xs:element name="fuse.version" type="xs:string" minOccurs="0"/>
			<xs:element name="fuse.zip" type="xs:anyURI" minOccurs="0"/>
			<xs:element name="fuse.path" type="xs:string" minOccurs="0"/>
			<xs:element name="start.wait.time" type="xs:integer" minOccurs="0"/>
			<xs:element name="stop.wait.time" type="xs:integer" minOccurs="0"/>
			<xs:element name="provision.wait.time" type="xs:integer" minOccurs="0"/>
			<xs:element name="patch.wait.time" type="xs:integer" minOccurs="0"/>
			<xs:element name="keepFolder" type="xs:string" minOccurs="0"/>
			<xs:element name="patch" type="xs:string" minOccurs="0"/>
			<xs:element name="fabric" type="xs:string" minOccurs="0"/>
			<xs:element name="fafram.working.directory" type="xs:string" minOccurs="0"/>
			<xs:element name="fafram.patch.dir" type="xs:string" minOccurs="0"/>
		</xs:all>
	</xs:complexType>


	<xs:complexType name="clusterType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="global" type="containerType"/>
			<xs:element name="containers" type="containersType"/>
		</xs:sequence>
	</xs:complexType>

	<!-- conf root element-->

	<xs:element name="fafram">
		<xs:complexType>
			<xs:all>
				<xs:element name="framework" type="frameworkType" maxOccurs="1"/>
				<xs:element name="cluster" type="clusterType" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jludvice/FaFram8/deployer/src/test/resources/parser_test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fafram xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="parser/configuration.scheme.xsd">

	<framework>
		<!-- Do not set this as it is not unset because these properties come from the surefire-plugin
		<fuse.group>testgroup</fuse.group>
		<fuse.id>testid</fuse.id>
		<fuse.version>testversion</fuse.version>
		-->
		<fuse.zip>testzip</fuse.zip>
		<fuse.path>testpath</fuse.path>
		<start.wait.time>999</start.wait.time>
		<stop.wait.time>999</stop.wait.time>
		<provision.wait.time>999</provision.wait.time>
		<patch.wait.time>999</patch.wait.time>
		<keepFolder>true</keepFolder>
		<patch>testpatch</patch>
		<fabric>testfabric</fabric>
		<fafram.working.directory>testdirectory</fafram.working.directory>
		<fafram.patch.dir>testdir</fafram.patch.dir>
	</framework>


	<!-- Framework settings settings -->
	<cluster>
		<!-- root default -->
		<global type="ROOT">
			<ssh host="openstack" username="fuse" password="fuse"/>
		</global>


	</cluster>


</fafram>
